target-version = "py310"
exclude = ["*_pb2.py"]

[lint]
select = [
  "E4",     # pycodestyle subset
  "E7",     # pycodestyle subset
  "E9",     # pycodestyle subset
  "F",      # pyflakes
  "I"       # isort
]
