target-version = "py310"
exclude = ["*_pb2.py", "*_pb2.pyi"]

[lint]
select = [
  "E4",     # pycodestyle subset
  "E7",     # pycodestyle subset
  "E9",     # pycodestyle subset
  "F",      # pyflakes
  "I",      # isort
  "UP",     # pyupgrade
]
ignore = [
  "E722",   # do not use bare except
  "E741",   # ambiguous variable name (seems to trigger on l, I, and such)
  "F841",   # unused local variable
]
