# SPDX-FileCopyrightText: 2023 Carnegie Mellon University - Satyalab
#
# SPDX-License-Identifier: GPL-2.0-only

filebeat.inputs:
  - type: log
    paths:
      - /openscout/server/openscout*.log
output.logstash:
  hosts: ["logstash:5044"]
setup.kibana:
  host: "kibana:5601"
filebeat.registry.path: /openscout/server/
