redis = "vm039.elijah.cs.cmu.edu"
redis_port = 6379
redis_user = "steeleagle"
redis_pw = "HcVFJAji1FK2/fSNnuImn1B6+JI="
webserver = "vm039.elijah.cs.cmu.edu:8080"
webrtc = "vm039.elijah.cs.cmu.edu:1984"
zmq = "172.26.44.244"
zmq_port = 6001
scripts_path = "/home/ubuntu/steeleagle/cnc/server/steeleagle-vol/scripts"
