services:
  steeleagle-os-driver:
    image: achanana/steeleagle-os-driver-olympe-arm:${TAG}
    # image: xianglic/steeleagle-os-driver-olympe-amd:${TAG}
    container_name: steeleagle-os-driver
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - STEELEAGLE_DRIVER_ARGS=${STEELEAGLE_DRIVER_ARGS}
      - STEELEAGLE_DRIVER_DRONE_ARGS=${STEELEAGLE_DRIVER_DRONE_ARGS}
      - TEL_PORT=${TEL_PORT}
      - CAM_PORT=${CAM_PORT}
      - CMD_BACK_PORT=${CMD_BACK_PORT}
      - CMD_ENDPOINT=${CMD_ENDPOINT}
      - RC_ENDPOINT=${RC_ENDPOINT}
      - ERROR_FREQUENCY=100
    entrypoint: ["python3", "driver.py"]
    restart: unless-stopped
    networks:
      - steeleagle-os-net

  steeleagle-os-kernel-cmd-svc:
    image: achanana/steeleagle-os-kernel:${TAG}
    container_name: steeleagle-os-kernel-cmd-svc
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - CMD_FRONT_PORT=${CMD_FRONT_PORT}
      - CMD_BACK_PORT=${CMD_BACK_PORT}
      - MSN_PORT=${MSN_PORT}
    ports:
      - "${CMD_FRONT_PORT}:${CMD_FRONT_PORT}"
      - "${CMD_BACK_PORT}:${CMD_BACK_PORT}"
      - "${MSN_PORT}:${MSN_PORT}"
    restart: unless-stopped
    privileged: true
    entrypoint: [ "python3", "CommandService.py"]
    networks:
      - steeleagle-os-net

  steeleagle-os-kernel-data-svc:
    image: achanana/steeleagle-os-kernel:${TAG}
    container_name: steeleagle-os-kernel-data-svc
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - STEELEAGLE_GABRIEL_SERVER=${STEELEAGLE_GABRIEL_SERVER}
      - STEELEAGLE_GABRIEL_PORT=${STEELEAGLE_GABRIEL_PORT}
      - TEL_PORT=${TEL_PORT}
      - CAM_PORT=${CAM_PORT}
      - LCE_PORT=${LCE_PORT}
    ports:
      - "${TEL_PORT}:${TEL_PORT}"
      - "${CAM_PORT}:${CAM_PORT}"
    restart: unless-stopped
    privileged: true
    entrypoint: [ "python3", "DataService.py"]
    networks:
      - steeleagle-os-net

  steeleagle-os-user:
    image: xianglic/steeleagle-os-user-arm:${TAG}
    # image: xianglic/steeleagle-os-user-amd:${TAG}
    container_name: steeleagle-os-user
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - CMD_FRONT_PORT=${CMD_FRONT_PORT}
      - MSN_PORT=${MSN_PORT}
      - CMD_ENDPOINT=${CMD_ENDPOINT}
    restart: unless-stopped
    privileged: true
    entrypoint: ["python3", "-m", "common.MissionController"]
    networks:
      - steeleagle-os-net
    volumes:
      - ./user/project/implementation:/steeleagle_os/user/project/implementation/

networks:

  steeleagle-os-net:
    ipam:
      driver: default
      config:
        - subnet: 13.13.0.0/24
