hub:
  network:
    cloudlet:
      endpoint: "gabriel-server"
      hub_to_gabriel: 9099
      commander_to_hub: 5003
    dataplane:
      endpoint: "0.0.0.0"
      driver_to_hub:
        telemetry: 3001
        image_sensor: 3002
      mission_to_hub: 3003
    controlplane:
      endpoint: "0.0.0.0"
      hub_to_driver: 3010
      hub_to_mission: 3005
      mission_to_hub: 3006
      mission_to_hub_2: 3007
      hub_to_datasink: 3008
  computes:
    - compute_id: 'default_compute'
      compute_class: 'GabrielCompute'
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "INFO"
    # Leave file as "" if you do not want to write the log
    log_file: "/configs/hub.log"
datasinks:
  # Comma-separated file paths for datasinks to register
  paths: "<PATH TO FILE 1,PATH TO FILE 2,...>"
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "INFO"
    # Leave file as "" if you do not want to write the log
    log_file: ""
mission:
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "INFO"
    # Leave file as "" if you do not want to write the log
    log_file: "/configs/mission.log"
driver:
  id: "kestrel"
  # Type of driver to run - must match a directory in drivers
  type: "multicopter"
  # Path to device file relative to type directory
  module: "devices.Parrot.Anafi"
    #connection_string: "10.202.0.1"
  connection_string: "10.5.5.2"
  #connection_string: "10.21.0.1"
  # For passing in device-specific flags
  keyword_args: {}
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "DEBUG"
    # Leave file as "" if you do not want to write the log
    log_file: "/configs/driver.log"
