[build-system]
requires = [
    "hatchling",
    "grpcio-tools>=1.71.2",
    "protobuf>=5.29.5",
    "protoletariat>=3.3.10",
    "Jinja2"
]
build-backend = "hatchling.build"

[project]
name = "steeleagle_sdk"
version = "1.0.0"
description = "SDK for interacting with SteelEagle vehicles."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    { name = "Mihir Bala", email = "mbala@andrew.cmu.edu" },
    { name = "Thomas Eiszler", email = "teiszler@andrew.cmu.edu" },
    { name = "Anthony Chen", email = "xianglic@andrew.cmu.edu" },
    { name = "Aditya Chanana", email = "achanana@andrew.cmu.edu" }
]
maintainers = [
  {name = "Thomas Eiszler", email = "teiszler@andrew.cmu.edu"}
]
keywords = [
    "autonomous",
    "robots",
    "edge",
    "vision",
    "drone",
    "uav",
    "uas",
    "ugv"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "protobuf>=3.12",
    "grpcio>=1.74.0",
    "pydantic>=2.11.7",
]

[project.urls]
Homepage = "https://cmusatyalab.github.io/steeleagle/"
Documentation = "https://cmusatyalab.github.io/steeleagle/"
Repository = "https://github.com/cmusatyalab/steeleagle"
Issues = "https://github.com/cmusatyalab/steeleagle/issues"
Changelog = "https://github.com/cmusatyalab/steeleagle/releases"

[tool.hatch.build]
directory = "build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
exclude = [
    "build/src/*"
]

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["build/src/steeleagle_sdk"]
include = [
    "build/src/steeleagle_sdk/**/*.py",
    "build/src/steeleagle_sdk/protocol/protocol.desc"
]

[tool.hatch.build.hooks.custom]
path = "build/prebuild.py"
