name: Build and push swarm controller

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/build-swarm-controller.yml'
      - 'backend/server/engines/swarm_controller/**'
      - 'protocols/**'
      - 'vehicle/util/**'

jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: steeleagle-swarm-controller
      dockerfile: backend/server/engines/swarm_controller/Dockerfile
    secrets: inherit
