name: Build and push vision engines

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ "v*" ]
    paths:
      - '.github/workflows/build-vision-engines.yml'
      - '.github/workflows/deploy-docker-img.yml'
      - 'backend/server/engines/avoidance/**'
      - 'backend/server/engines/detection/**'
      - 'backend/server/engines/Dockerfile.obj_avoid'
      - 'backend/server/engines/requirements.obj_avoid.txt'
      - 'backend/server/engines/watermark.png'
      - 'protocol/**'
      - 'vehicle/util/**'

jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: steeleagle-vision-engines
      dockerfile: backend/server/engines/Dockerfile.obj_avoid
      free_disk_space: true
    secrets: inherit
