name: Build and push telemetry engine

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ "v*" ]
    paths:
      - '.github/workflows/build-telemetry-engine.yml'
      - '.github/workflows/deploy-docker-img.yml'
      - 'backend/server/engines/telemetry/**'
      - 'protocol/**'
      - 'vehicle/util/**'

jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: steeleagle-telemetry-engine
      dockerfile: backend/server/engines/telemetry/Dockerfile.telemetry
    secrets: inherit
