name: Build and push vision engines

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-vision-engines.yml'
      - 'vehicle/util/**'
      - 'protocol/**'
      - 'backend/server/engines/detection/**'
      - 'backend/server/engines/avoidance/**'
      - 'backend/server/engines/Dockerfile.obj_avoid'
      - 'backend/server/engines/requirements.obj_avoid.txt'

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: false

    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Download protobuf compiler
      run: wget https://github.com/protocolbuffers/protobuf/releases/download/v29.4/protoc-29.4-linux-x86_64.zip

    - name: Unzip protobuf compiler
      run: unzip -d protobuf protoc-29.4-linux-x86_64.zip

    - name: Build protobufs
      run: cd protocol && PROTOC_PATH=../protobuf/bin/protoc ./build.sh

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push vision engine image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: backend/server/engines/Dockerfile.obj_avoid
        push: true
        tags: cmusatyalab/steeleagle-vision-engines:latest
        cache-from: type=registry,ref=cmusatyalab/steeleagle-vision-engines:latest
        cache-to: type=inline
