name: Deploy SteelEagle Docker image

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      free_disk_space:
        description: 'Whether to free disk space in the runner'
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: false
      if: ${{ inputs.free_disk_space }}

    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Download protobuf compiler
      run: wget https://github.com/protocolbuffers/protobuf/releases/download/v29.4/protoc-29.4-linux-x86_64.zip

    - name: Unzip protobuf compiler
      run: unzip -d protobuf protoc-29.4-linux-x86_64.zip

    - name: Build protobufs
      run: cd protocol && PROTOC_PATH=../protobuf/bin/protoc ./build.sh

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Docker image tag
      id: get_tag
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "tag=latest" >> "$GITHUB_OUTPUT"
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          echo "tag=dev" >> "$GITHUB_OUTPUT"
        fi

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: cmusatyalab/${{ inputs.name }}:${{ steps.get_tag.outputs.tag }}
        cache-from: type=registry,ref=cmusatyalab/steeleagle-swarm-controller:${{ steps.get_tag.outputs.tag }}
        cache-to: type=inline
