services:
  core:
    endpoint: 'unix:///tmp/core.sock'
  driver:
    endpoint: 'unix:///tmp/driver.sock'
  mission:
    endpoint: 'unix:///tmp/mission.sock'
  flight_log:
    endpoint: 'unix:///tmp/log.sock'
  testing:
    endpoint: 'unix:///tmp/test.sock'
streams:
  driver_telemetry:
    endpoint: 'unix:///tmp/driver_telem.sock'
  mission_telemetry:
    endpoint: 'unix:///tmp/mission_telem.sock'
  imagery:
    endpoint: 'unix:///tmp/imagery.sock'
  results:
    endpoint: 'unix:///tmp/results.sock'
