[vehicle]
name = '<NAME>'
# Script is relative to the vehicle directory; the launch script
# will attempt to run this file as a subprocess
package = 'path/to/executable'
kwargs = {}

[cloudlet]
swarm_controller = 'localhost:9005'
remote_compute_service = 'localhost:9006'

[logging]
# Whether or not to create an MCAP flight log for mission replay
generate_flight_log = true
# Whether or not to log to console
log_to_console = true
# Log to a custom filename; otherwise will autogenerate
# a name based on name, date, and time if empty string
# is provided
custom_filename = '' 
# Path to log file
file_path = './kernel/logs/'
# Log level
log_level = 'DEBUG'
