hub:
  data_endpoint: "0.0.0.0"
  command_endpoint: "0.0.0.0"
  ports:
    data_port:
      driver_to_hub:
        telemetry: 0
        image_sensor: 0
      hub_to_mission:
        telemetry_results: 0
        compute_results: 0
    command_port:
      hub_to_driver: 0
      hub_to_mission: 0
      hub_to_datasink: 0
      backend_to_hub: 0
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "<LOG LEVEL>"
    log_file: "<FILENAME>"
datasinks:
  # Comma-separated file paths for datasinks to register 
  paths: "<PATH TO FILE 1,PATH TO FILE 2,...>"
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "<LOG LEVEL>"
    log_file: "<FILENAME>"
mission:
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "<LOG LEVEL>"
    log_file: "<FILENAME>"
driver:
  id: "<DRONE NAME>"
  path: "<PATH TO FILE>"
  connection_string: "0.0.0.0:0"
  # For passing in device-specific flags
  keyword_args: {}
  logging:
    # Log level can be one of {INFO, DEBUG, WARNING, ERROR}
    log_level: "<LOG LEVEL>"
    log_file: "<FILENAME>"
