services:
  kestrel:
    image: cmusatyalab/steeleagle-vehicle
    container_name: vehicle
    environment:
      - CONFIG_PATH=/configs/config.yaml
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    networks:
      - cnc-net
    volumes:
      - ./configs/kestrel:/configs

networks:
  cnc-net:
    external: true
